# .project metadata for Serverless Devs
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Set slack_channels
# TODO: Add adopters list (ADOPTERS.md)
# TODO: Add package_managers if distributed via registries

schema_version: "1.0.0"
slug: "serverless-devs"
name: "Serverless Devs"
description: "Serverless Devs developer tool ( Serverless Devs 开发者工具 )"
type: "project"
project_lead: "anycodes" # TODO: AUTO-DETECTED — please verify
# TODO: Set CNCF Slack channel(s)
# slack_channels:
#   - name: "#serverless-devs"
#     primary: true

maturity_log:
  - phase: "sandbox"
    date: "2022-09-14T00:00:00Z"
    issue: "https://github.com/cncf/sandbox/issues/169" # TODO: AUTO-DETECTED — please verify

repositories:
  - "https://github.com/serverless-devs/serverless-devs"

website: "https://www.serverless-devs.com/"

artwork: "https://landscape.cncf.io/logos/serverless-devs.svg"

# TODO: Add ADOPTERS.md if your project tracks adopters
# adopters:
#   path: "https://github.com/Serverless-Devs/Serverless-Devs/blob/master/ADOPTERS.md"


# TODO: Add package manager identifiers if your project is distributed via registries
# package_managers:
#   docker: "Serverless-Devs/Serverless-Devs"


security:
  policy:
    path: "https://github.com/Serverless-Devs/Serverless-Devs/blob/master/SECURITY.md"
  contact:
    advisory_url: "https://github.com/Serverless-Devs/Serverless-Devs/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/Serverless-Devs/Serverless-Devs/blob/master/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/Serverless-Devs/Serverless-Devs/blob/master/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/Serverless-Devs/Serverless-Devs/blob/master/LICENSE"
  identity_type:
    has_dco: true # AUTO-DETECTED — please verify
    has_cla: false # AUTO-DETECTED — please verify
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/Serverless-Devs/Serverless-Devs/blob/master/README.md"

landscape:
  category: "Orchestration & Management"
  subcategory: "Scheduling & Orchestration"

# CLOMonitor Score: 51/100
# Documentation: 45 | License: 90 | Best Practices: 7 | Security: 27
